namespace EshopPOC.API
{
    public enum ErrorCode
    {
        USER_NOT_LOGGED_IN = 100,
        USER_NOT_AUTHORIZED = 101,
        USER_ALREADY_EXISTS = 102,
        USER_WRONG_PASSWORD = 103,
        USER_ALREADY_LOGGED_IN = 104,
        DB_SAVE_ERROR = 200,
        DB_FIND_ERROR = 201,
        DB_ITEM_NOT_FOUND = 202,
        DB_UPDATE_ERROR = 203,
        DB_REMOVE_ERROR = 204,
        DB_COUNT_ERROR = 205,
        DB_AGGREGATE_ERROR = 206,
        DB_INVALID_ID_ERROR = 207,
        REQUEST_MISSING_PARAMS = 300,
        REQUEST_INVALID_PARAMS = 301,
        REQUEST_VALIDATION_ERROR = 302,
        UNKNOWN_ERROR = 900,
        UNITY_WWW_ERROR = 1000
    }
}